Repository halo-sigs/plugin-alist, pull requests merged in 2024-07, with the labels that each got.

#1 Initialize project
  .editorconfig
  .github/workflows/ci.yaml
  .gitignore
  LICENSE
  OWNERS
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/run/halo/starter/AListAttachmentHandler.java
  src/main/java/run/halo/starter/AListPlugin.java
  src/main/resources/extensions/policy-template-alist.yaml
  src/main/resources/extensions/settings.yaml
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
  ui/.editorconfig
  ui/.eslintrc.cjs
  ui/.gitignore
  ui/env.d.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/assets/logo.svg
  ui/src/index.ts
  ui/src/views/HomeView.vue
  ui/tsconfig.app.json
  ui/tsconfig.json
  ui/tsconfig.node.json
  ui/tsconfig.vitest.json
  ui/vite.config.ts
Labels: release-note-none, lgtm

#2 Adapt AList basically
  README.md
  docs/img/1.png
  docs/img/2.png
  docs/img/3.png
  docs/img/4.png
  docs/img/5.png
  docs/img/6.png
  docs/img/7.png
  docs/img/8.png
  gradle.properties
  src/main/java/run/halo/alist/AListPlugin.java
  src/main/java/run/halo/alist/config/AListProperties.java
  src/main/java/run/halo/alist/controller/PolicyConfigValidationController.java
  src/main/java/run/halo/alist/dto/AListResult.java
  src/main/java/run/halo/alist/dto/request/AListGetFileInfoReq.java
  src/main/java/run/halo/alist/dto/request/AListLoginReq.java
  src/main/java/run/halo/alist/dto/request/AListRemoveFileReq.java
  src/main/java/run/halo/alist/dto/response/AListGetFileInfoRes.java
  src/main/java/run/halo/alist/dto/response/AListLoginRes.java
  src/main/java/run/halo/alist/dto/response/AListStorageListRes.java
  src/main/java/run/halo/alist/dto/response/AListUploadAsTaskRes.java
  src/main/java/run/halo/alist/endpoint/AListAttachmentHandler.java
  src/main/java/run/halo/alist/exception/AListIllegalArgumentException.java
  src/main/java/run/halo/alist/exception/AListRequestErrorException.java
  src/main/java/run/halo/starter/AListAttachmentHandler.java
  src/main/resources/extensions/policy-template-alist.yaml
  src/main/resources/extensions/settings.yaml
  src/main/resources/plugin.yaml
  ui/pnpm-lock.yaml
Labels: release-note-none, approved, lgtm

#4 chore: update project infrastructure
  .github/workflows/cd.yaml
  .github/workflows/ci.yaml
  OWNERS
  build.gradle
  src/main/resources/extensions/policy-template-alist.yaml
  src/main/resources/plugin.yaml
  ui/.editorconfig
  ui/.eslintrc.cjs
  ui/.gitignore
  ui/env.d.ts
  ui/package.json
  ui/pnpm-lock.yaml
  ui/src/assets/logo.svg
  ui/src/index.ts
  ui/src/views/HomeView.vue
  ui/tsconfig.app.json
  ui/tsconfig.json
  ui/tsconfig.node.json
  ui/tsconfig.vitest.json
  ui/vite.config.ts
Labels: release-note-none, approved, kind/improvement, lgtm
